meshing:
    num_workers: 12
    mesh_size: 600  # spacings between mesh grids in pixel at mip0
    simplify_tol: 2 # when approximate regions defined by mask images to polygon, the tolerance of distance error
    mask_dir: null  # the folder contains the material masks. if set to null, default to working_directory/align/material_masks. If mask not exist in this folder, use the one in the thumbnail folder     
    mask_mip_level: 4 # the resolution of the masks in mask_dir folder
    area_thresh: 25 # regions with area smaller than the threshold will be discarded

matching:
    working_mip_level: 2  # resolution at which to do the matching
    match_name_delimiter: __to__    # so that the match file follows the patern sec0{delimieter}sec2.h5
    loader_config:
        cache_size: 60  # total number of source images allowed to cache in RAM
    matcher_config:
        num_workers: 12
        batch_size: 100 # number of cropped regions to do fft at the same time
        conf_thresh: 0.35    # cross-correlations with confidence value smaller than this will be rejected
        sigma: 3.5
        pad: true
        distributor: cartesian_region   # cartesian_region/intersect_triangulation/oneway_triangulation
        spacings: [400, 100]    # distance between grid points at each coarse-to-fine level
        shrink_factor: 0.7  # the size of the cropped fft tiles compared to the spacings
        residue_mode: huber # huber or threshold or None, deciding how to damp matches with large residue errors after optimization
        residue_len: 3  # characteristic residue distance used for damping. use 0 to skip
        min_boundary_distance: 20   # minimum distance allowed from a matching point to the boundary of the meshes
        boundary_tolerance: 20  # maximum distance between grid points when distributor=='oneway_triangulation'

optimization:
    stack_config:
        mip_level: 0
        mesh_cache_size: 90
    slide_window:
        num_workers: 2
        start_loc: M
        window_size: 64
        buffer_size: 16
        residue_mode: huber
        residue_len: 20
        elastic_params:
            tol: 1.0e-7
            atol: 0.001
            continue_on_flip: true
            callback_settings:
                timeout: null
                early_stop_thresh: null
                chances: null
                eval_step: 10

rendering:
    offset_bbox: true
    out_dir: null  # directory to save the aligned stack. if set to null, default to working_directory/aligned_stack
    num_workers: 10
    pattern: _tr{ROW_IND}-tc{COL_IND}.png
    one_based: true # zero-based or one-based row/colume indexing
    max_tile_per_job: 20
    mip_level: 0
    canvas_bbox: null
    tile_size: [4096, 4096]
    remap_interp: LANCZOS # LANCZOS | CUBIC | LINEAR | NEAREST
    loader_config:
        cache_size: 50
        fillval: 0
        apply_CLAHE: false

downsample:
    num_workers: 10
    parallel_within_section: true   # whether to parallel among tiles within a section, or among sections
    max_mip: 7
    format: jpg
