working_directory: ./work_dir   # project specific working directory
output_stitch_directory: null   # directory to save the stitched images. if set to null, default to working_directory/stitched_sections
output_aligned_directory: null  # directory to save the aligned stack. if set to null, default to working_directory/aligned_stack

cpu_budget: 20      # CPU cores to use (estimated target only, no hard control)

# logging configs
logging_directory: null # directory to save log files. if set to null, default to working_directory/logs
logfile_level: WARNING  # DEBUG, INFO, WARNING, ERROR or NONE
console_level: INFO
archive_level: INFO